Set: node version.
gamitee-dev/html-fairy pull request #402
Opened 2024-04-30 12:54 UTC by Pruthvi-iamops

Closes #399

2024-04-30 19:23 UTC, tomerle commented on .github/workflows/deploy.yml
> +          node-version-file: package.json
🤩

2024-04-30 19:31 UTC, tomerle requested changes
I only commented on what we see here. Still need to make sure everything requested in the Issue is covered by the PR.

_@Pruthvi-iamops, good stuff in the places you chose solutions better than what I requested._

2024-04-30 19:31 UTC, tomerle commented on .github/workflows/deploy.yml
> +          node-version-file: package.json
I see logic in calling all setup Actions first, but seems more security-oriented to cal `actions/setup-node` below, just before we actually use `npm` (i.e. `node`).

2024-04-30 19:31 UTC, tomerle commented on .github/workflows/linter.yml
> +        run: npm run eslint:test
We actually like an EOL (End Of Line) at the EOF (End Of File). 🙏 🤓

2024-04-30 19:31 UTC, tomerle commented on .npmrc
> +update-notifier=false
We actually like an EOL (End Of Line) at the EOF (End Of File). 🙏 🤓

2024-04-30 19:31 UTC, tomerle commented on package-lock.json
@Pruthvi-iamops, this is the result of running `npm run reinstall`, right?

2024-05-02 10:49 UTC, Pruthvi-iamops commented on package-lock.json
@tomerle Yes this are the result of the npm run reinstall which I ran from my local machine.

2024-05-02 10:56 UTC, tomerle commented on package-lock.json
Thanks! Asking you was my way of reviewing this. 😎

2024-05-02 10:59 UTC, tomerle commented on package.json
@Pruthvi-iamops, please run `npm i --save-dev @types/node@20 && npm ci` and push again. 🙏

2024-05-02 11:24 UTC, tomerle approved these changes

2024-05-02 11:24 UTC, merged